name = "Server Modpack"
author = "Almino Melo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee9b1b6d1fbfddbd184a0154779cb47071fd6098e816d88b8cc2277d027d068b"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
